# Generated by Django 3.2.23 on 2024-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('complaint', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=45)),
                ('time', models.CharField(max_length=45)),
                ('reply', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
    ]
