# Generated by Django 3.2.23 on 2024-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertDetails',
            fields=[
                ('cert_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cert_details',
            },
        ),
    ]
