# Generated by Django 3.2.23 on 2024-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertRequest',
            fields=[
                ('cert_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_details_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=45)),
                ('proof', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cert_request',
            },
        ),
    ]
