# Generated by Django 3.2.23 on 2024-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('u_id', models.IntegerField()),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
