# Generated by Django 3.2.23 on 2024-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('job_vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=45)),
                ('designation', models.CharField(max_length=45)),
                ('qualification', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'job_vacancy',
            },
        ),
    ]
