# Generated by Django 3.2.23 on 2024-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('job_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_vacancy_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('resume', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'job_application',
            },
        ),
    ]
