# Generated by Django 3.2.23 on 2024-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('features', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('authority_id', models.IntegerField()),
            ],
            options={
                'db_table': 'feature',
            },
        ),
    ]
