# Generated by Django 3.2.23 on 2024-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('authority_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'authority',
            },
        ),
    ]
