# Generated by Django 3.2.23 on 2024-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
                ('house_name', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
                ('pin_code', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
